apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  # name: java-pipelinerun
  generateName: java-pipelinerun-
spec:
  pipelineRef:
    name: java-pipeline
  serviceAccountName: tekton-github-sa
  workspaces:
    - name: shared-workspace
      persistentvolumeclaim:
        claimName: tkn-shared-workspace-pvc
    - name: maven-settings
      configMap:
        name: maven-settings-store
    - name: docker-config
      configMap:
        name: docker-config-store
    - name: input-asset
      emptyDir: {}
      # configMap:
      #   name: input-asset-store
  params:
    - name: git-code-repo-url
      value: https://github.com/USER_NAME/CODE_REPOSITORY.git
    - name: git-code-branch-name
      value: master
    - name: git-code-subdir
      value: ""
    - name: git-cd-repo-url
      value: https://github.com/USER_NAME/CD_REPOSITORY.git
    - name: git-cd-branch-name
      value: master
    - name: git-cd-subdir
      value: ""
    - name: git-cd-user-name
      value: USER_NAME
    - name: git-cd-user-email
      value: USER_EMAIL
    - name: git-cd-script
      value: |
        RELEASE_VERION="0.0.1"

        git branch release-${RELEASE_VERION}
        git checkout release-${RELEASE_VERION}

        # cp $(workspaces.input.path)/* $(workspaces.source.path)
        sed -i "s/RELEASE_VERION/${RELEASE_VERION}/g" ./base/*.yaml
        git add .

        git commit -m "release-${RELEASE_VERION}" --allow-empty
        git push origin release-${RELEASE_VERION}

    - name: maven-goals
      value:
        # - -DskipTests
        - clean
        - deploy
    - name: maven-context-dir
      value: ./
    - name: kaniko-image
      value: my-docker-registry.registry-system:5000/IMAGE:TAG
    - name: kaniko-dockerfile
      value: ./Dockerfile
    - name: kaniko-context
      value: ./
    - name: kaniko-extra-args
      value:
        - --insecure-registry=my-docker-registry.registry-system:5000
        - --insecure-registry=sonatype-nexus-service.nexus-system:5003
        - --registry-mirror=sonatype-nexus-service.nexus-system:5003
        - --verbosity=info
    - name: kaniko-builder-image
      value: gcr.io/kaniko-project/executor:latest
