apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  # name: java-pipelinerun
  generateName: java-pipelinerun-
spec:
  pipelineRef:
    name: java-pipeline
  serviceAccountName: git-build-bot
  workspaces:
    - name: shared-workspace
      persistentvolumeclaim:
        claimName: tkn-shared-workspace-pvc
    - name: maven-settings
      configMap:
        name: maven-settings-store
    - name: docker-config
      configMap:
        name: docker-config-store
  params:
    - name: git-repo-url
      value: https://github.com/USERNAME/REPOSITORY.git
    - name: git-branch-name
      value: master
    - name: maven-goals
      value:
        # - -DskipTests
        - clean
        - deploy
    - name: maven-context-dir
      value: ./
    - name: kaniko-image
      value: my-docker-registry.registry-system:5000/IMAGE:TAG
    - name: kaniko-dockerfile
      value: ./Dockerfile
    - name: kaniko-context
      value: ./
    - name: kaniko-extra-args
      value:
        - --insecure-registry=my-docker-registry.registry-system:5000
        - --insecure-registry=sonatype-nexus-service.nexus-system:5003
        - --registry-mirror=sonatype-nexus-service.nexus-system:5003
        - --verbosity=info
    - name: kaniko-builder-image
      value: gcr.io/kaniko-project/executor:latest
